# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe91df7165a0a6a35e115d2d8d377218b216a258990c600371f691f6cb53cfee5bf01025b8d46e14f28f37fffce620bf59326bfb777e205b30ce74b91dfd3743

test:
  secret_key_base: 61677a425dfcad5e73eed30b7850e8a2ab6803ad5bfa806f7a3a566b4bd93a6b55b90bf713f5198b2e5bbd6340c79dfd17ae1f5c771fba159c74c7bc388c2995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
